version: '2.0'
services:
  caddy:
    image: abiosoft/caddy
    restart: always
    volumes:
    - ./Caddyfile:/etc/Caddyfile:ro
    - ./caddyCertificates:/root/.caddy
    - /etc/letsencrypt:/etc/letsencrypt
    environment:
    - ACME_AGREE=true
    ports:
    - "80:80"
    - "443:443"
  dnsrobocert:
    image: adferrand/dnsrobocert
    container_name: dnsrobocert
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt
    - /etc/dnsrobocert:/etc/dnsrobocert
    restart: always